### ISSUE TITLE
Installed ROCm4.0, but how to use it?

### ISSUE THREAD

**Issue by oconnor127** [aieater/rocm_pytorch_informations#13]
Hey, 
I just installed ROCm4.0 from the official pytorch website. How can I now use my radeon gpu for training?
I tried your command:

python3 -c 'import torch;print("DeviceName:",str(torch.cuda.get_device_name(torch.cuda.current_device())))'

which gives the error

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/bryan/.local/lib/python3.6/site-packages/torch/cuda/__init__.py", line 388, in current_device
    _lazy_init()
  File "/home/bryan/.local/lib/python3.6/site-packages/torch/cuda/__init__.py", line 170, in _lazy_init
    torch._C._cuda_init()
RuntimeError: No HIP GPUs are available

Any clues what I am doing wrong or could you give me any hint, how to use my gpu after installing ROCm4.0?

Thanks in advance

**Comment by SantaSheep** [comment]
Hi @oconnor127,

This error could be caused because the installation failed or your gpu isn't supported for this generation of rocm.  These instructions are old and for previous versions of rocm and can contain incomplete information. Most likely something in the install process failed, can you provide me with your gpu model and some other debugging information please?
